<?php

require 'headerx.php';

?>



<script src='main1.js'></script>
  
  <link rel='stylesheet' type='text/css' href='terms.css'>

    <!-- ======= Featured Services Section ======= -->
    <section id="featured-services" class="featured-services">

    <!-- ======= Services Section ======= -->
<section id="" class="services_terms">
<div class="" style=' font-style:arial; padding-right:10%; padding-left:10%; line-height:35px;' >
<h2>Terms Of Use<h2>
<h4> Last Updated on October 1, 2018 </h4>
The website  yourmccluredesigns.org (the “Site”) is brought to you by  yourmccluredesigns.org Inc. (“ yourmccluredesigns.org,” “we,” “us,” or “our”).

Your acceptance of the terms of use. Please read these terms and conditions of use (the “Terms of Use” or “User Agreement”) carefully before using the site as they constitute a legally binding contract between you and  yourmccluredesigns.org. This User Agreement sets forth the terms and conditions which govern your access and use of the Site and of the Content (as defined below) and the services and functionality made available on or through the Site (collectively, the “Services”) whether as a guest or a registered user. By browsing, accessing, or otherwise using the Services in any manner, you hereby accept, without limitation or qualification, (1) the Terms of Use and (2) the Privacy Policy for the site (the “Privacy Policy”). If you do not agree to these Terms of Use or the Privacy Policy, please do not use the Services and exit now. Further, if you do not agree to these Terms of Use or the Privacy Policy, you agree that your sole and exclusive remedy is to discontinue using this Site.

Updates/revisions to the terms of use. Please review the terms of use periodically. We reserve the right, in our sole discretion, to update or revise these Terms of Use at any time. By using or accessing the Site, you agree that we may modify the Terms of Use or the Site at any time without prior notice. You further agree that we will have no further obligation to notify you of any modifications and such updates or modifications shall become effective immediately upon the posting thereof. Such updates or revisions shall become effective immediately upon the posting thereof. Your continued use of the Site following the posting of updates and/or revisions to the Terms of Use will conclusively indicate and constitute your acceptance of such update and/or revised Terms of Use. The most current version of the Terms of Use can be accessed at any time by selecting Terms of Use link on the bottom of the home page for the Site.


<h3> Security of your username/password </h3>
Access to the certain areas of the Services (“User Restricted Areas”) is enabled only by username and password. You shall maintain your password in strict confidence. In no event shall you share your password with any third party or allow another person to access the User Restricted Areas using your password. You shall immediately notify us if you have any reason to believe that your username or password has been lost or compromised or misused in any way. You shall immediately report any unauthorized or suspicious activity in your account. You are fully and solely responsible for any and all use of the Services using your username and password. We reserve the right to revoke or deactivate your username and password if you violate the terms of this User Agreement.


<h2> Content made available on or through the site and your use of content </h2>
<h3>Description of Content. </h3>
<p> A. The Site contains a wide variety of Content (defined below), whether (1) proprietary to  yourmccluredesigns.org and its affiliates, or (2) proprietary to third parties. “Content” includes, but is not limited to text, data, files, documents, software, scripts, layout, design, function and “look and feel,” graphics, images, audio, videos, audiovisual combinations, interactive features and any other materials that you may view, access or download (but only as expressly permitted in paragraph C below) through the Site. </p>

<h3> B. Proprietary Rights. </h3>
You acknowledge and agree that all Content, whether publicly posted or privately transmitted, as well as all derivative works thereof, are owned by  yourmccluredesigns.org or other parties that have licensed their material to  yourmccluredesigns.org, and are protected by copyright, trademark, and other intellectual property laws. Except as specifically permitted herein, Content may not be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way, including by e-mail or other electronic means, without the prior consent of  yourmccluredesigns.org or such third-party that owns the Content. All rights not expressly granted herein by  yourmccluredesigns.org and/or its licensors to you are reserved by  yourmccluredesigns.org and/or its licensors.

<h3> C. Restrictions on Your Use of Content. </h3>
 You may access and use Content solely for your information and personal, non-commercial use, as intended through the provided functionality of the Services and permitted under this User Agreement. Any modification of the Content, use of the Content on any web site or networked computer environment, or use of the Content for any purpose other than personal, non-commercial use, without the prior consent of  yourmccluredesigns.org or its licensors, as applicable, is a violation of the copyright, trademark, and other proprietary rights in the Content and is expressly prohibited. You agree not to circumvent, disable or otherwise interfere with security-related features of the Services that prevent or restrict the use or copying of any Content and not to alter, remove, or falsify any attributions or other proprietary designations of origin or source of any Content appearing on the Site. You shall not download any Content unless you see a “download” or similar link displayed by us on the Site for such Content. We do not have an obligation to detect the presence of Harmful Code (as defined in “Restrictions on the use of your Services” below). If you download any Content from the Site, you do so at your own risk. You agree that you are responsible for your own conduct while using the Site or Services and for any consequences thereof. You agree to use the Services only for purposes that are legal, proper and in accordance with this User Agreement, the Privacy Policy, and any applicable law, rules or regulations (including, without limitation, the Securities Act of 1933, the Securities Exchange Act of 1934, the Investment Company Act of 1940, the Investment Advisers Act of 1940, any applicable state “Blue Sky” laws, any other applicable United States federal or state securities laws, regulations and rules, any securities exchange or self-regulatory organization’s rules or regulations, any consumer protection, unfair competition, and anti-discrimination laws or regulations and any applicable foreign laws).

<h3> D. Disclaimer. </h3>
Your use of the Services is at your sole risk and Content is provided to you on an AS IS and AS AVAILABLE basis. You understand that we do not guarantee the accuracy, safety, integrity or quality of Content and you hereby agree that you must evaluate and bear all risks associated with the use of any Content, including any reliance on the Content, integrity, and accuracy of such Content. Nothing on the Site should be deemed to constitute a recommendation to purchase, sell or hold, or otherwise to constitute advice regarding, any registered or unregistered security. By accessing Content you acknowledge and agree that  yourmccluredesigns.org does not engage in the business of effecting securities transactions or providing investment advice and is not registered with the U.S. securities and exchange commission or any state securities regulator as a broker-dealer or investment adviser and does not conduct any activity that would require such registration.
</p>

<h3> Non-disclosure and confidentiality </h3>
In using the Services, you will have access to confidential information of  yourmccluredesigns.org and its affiliates and their respective clients, borrowers, originators, brokers, licensors and suppliers that may include, but is not limited to the names, business and financial information, business plans, operating agreements, investment memorandums, and customer names of  yourmccluredesigns.org’s and its affiliates’ clients (collectively, “Confidential Information”). You agree to maintain and safeguard vigilantly the privacy and security of all Confidential Information. Without limiting the foregoing, you agree to undertake all necessary measures to ensure the privacy and security of all Confidential Information including without limitation: (i) to use the Confidential Information only for the purpose for which such Confidential Information was made available to you as a part of the Services (the “Permitted Purpose”) and for no other purpose whatsoever; (ii) not to access, use or disclose any Confidential Information that you have no legitimate authorization to access, use or disclose; (iii) not to access the Services or any Confidential Information for any other individual (except to the extent fully disclosed by you to  yourmccluredesigns.org) or any unauthorized third party; (iv) not to disclose Confidential Information to any third-party except to your attorneys and financial advisors who need to know such information to assist you to carry out the Permitted Purpose (the “Representatives”) and which Representatives are bound by a written confidentiality agreement containing disclosure and use provisions no less restrictive with respect to disclosure than those set forth herein; (v) to restrict physical and system access to the equipment which contains Confidential Information or which gives access to the Confidential Information (such as by diligently locking and monitoring office premises and requiring password verification to gain access to desktop computers); and (vi) to use Confidential Information in compliance with all applicable laws. You shall immediately notify, and cooperate fully with  yourmccluredesigns.org in the event you discover or suspect any unauthorized use of or access to the Services and/or Confidential Information. You hereby agree that you shall be responsible hereunder for any breach or threatened breach by the Representatives of the obligations set forth in this section as if such breach or threatened breach was committed by you. You acknowledge and further agree that all obligations relating to Confidential Information under this User Agreement will continue after termination of this User Agreement and termination of access rights hereunder.


<h3> Restrictions on your use of the services </h3>
You agree not to access or use the Services in an unlawful way or for an unlawful or illegitimate purpose, including without limitation any violation of the antifraud or registration provisions of the securities laws of the U.S. or any state therefore. You shall not post or transmit via the Services (a) a message or information under a false name; (b) information that is unlawful, libelous, defamatory, obscene, fraudulent, predatory of minors, harassing, threatening or hateful to any person; or (c) information that infringes or violates any of the intellectual property rights of others or the privacy or publicity rights of others. You shall not attempt to disrupt the operation of the Services in any manner, including, but through the use of methods such as denial of service attacks, flooding or spamming and you will not transmit, distribute, introduce or otherwise make available in any manner through the Services any computer virus, keyloggers, spyware, worms, Trojan horses, time bombs or other malicious or harmful code (collectively, “Harmful Code”). You shall not use the Services in any manner that could damage, disable or impair our services or networks. You shall not attempt to gain unauthorized access to any user accounts or computer systems or networks, through hacking, password mining or any other means. You shall not use any robot, scraper or other means to access the Services.


<h3> Trademarks/service marks, logos, slogans and taglines </h3>
All trademarks, service marks, logos, slogans and taglines displayed on or through the Services are the property of  yourmccluredesigns.org® or their respective owners and nothing contained herein should be construed as granting any license or right to use any trademarks, service marks, logos, slogans or taglines displayed on or through the Services without the express written permission of  yourmccluredesigns.org, or such third-party that may own the trademark, service mark, logo, slogan or tagline.


<h3> Copyright complaints </h3>
If you believe that any Content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing us with the information in writing as outlined in 17 U.S.C 512(c)(3). Please send notices to:
<h4>  yourmccluredesigns.org Inc. </h4>
1450 E Main Street, </br>
Apt 307 Hazard, KY 41701, </br>
United States of America</br>
<span> support@yourmccluredesigns.org </span>
<p> You acknowledge that if you fail to comply with all of the requirements of 17 U.S.C. 512 (c)(3), your DMCA notice may not be valid.</p>


<h3> Electronic Fund Transfers (“EFTs”) and Account Balances </h3>
By creating an account with  yourmccluredesigns.org and initiating bank deposits or withdraws (i.e. EFTs), you agree to the terms of service and privacy policy of our financial software provider, Synapse Financial Technologies, Inc. (“Synapse”), and Synapse’s financial institution partner’s Terms of Service & Privacy Policy (collectively, “Synapse TOS”) which are incorporated herein by reference. Terms not defined in this section shall be defined in Synapse TOS. Bank services are provided by Evolve Bank & Trust, Member FDIC, through Synapse, and you hereby authorize  yourmccluredesigns.org’s use of Evolve Bank & Trust’s services.

We have partnered with Synapse, a financial services software company, to provide payments services. When you sign up for an account with our Platform, you will also be signing up for a Synapse account (a “User Account”). You authorize us to share your identity and banking information with Synapse to open and support your User Account as further detailed in our Privacy Policy and Synapse’s Privacy Policy. By creating a User Account you acknowledge that Synapse may share user data as necessary with their financial partners and other service providers in connection with providing their respective services. It is your responsibility to make sure the data you provide us is accurate and complete. Additionally, you are responsible for complying with Synapse TOS when using your User Account. It is your responsibility to read and understand Synapse TOS as it contains terms and conditions relating to your User Account including but not limited to your rights, limitations, reversal and other liabilities, limitation of liability and binding arbitrations provisions.

When you open a User Account, you will link a checking or savings account to perform EFT and, if applicable, deposit funds into your User Account. Deposits into your User Account are held at Synapse’s financial institution partners as detailed in Synapse TOS. DEPOSITS HELD IN A USER ACCOUNT MAY BE ELIGIBLE FOR INSURANCE BY THE FEDERAL DEPOSIT INSURANCE CORPORATION (“FDIC”) ON A PER USER BASIS DEPENDING ON THE RULES AND LIMITATIONS SET FORTH BY THE FDIC. FOR PURPOSES OF APPLICABLE FDIC DEPOSIT INSURANCE LIMITATIONS, DEPOSITS IN ACCOUNTS AT THE FINANCIAL INSTITUTIONAL PARTNER(S) OPENED THROUGH THE FINANCIAL INSTITUTIONAL PARTNER(S) WITH SYNAPSE MAY NOT BE SEPARATELY INSURED FROM ANY OTHER ACCOUNTS YOU MAY HAVE OPENED WITH THE FINANCIAL INSTITUTIONAL PARTNER(S), DEPENDING ON THE NAMED ACCOUNT OWNERS.

All EFT transactions are performed by and deposits are held by Synapse’s financial institution partner.  yourmccluredesigns.org and Synapse only transmit transaction instructions to Synapse financial institution partner.  yourmccluredesigns.org will provide you with all transaction’s notifications and User Account balances in addition to providing customer support relating to your User Account as detailed below.

<h3> Multi-Bank Program</h3>

As you participate in the Multi-Bank Program, your funds will be swept to one or more program banks and will be eligible for FDIC insurance. FDIC Insurance is not provided until the funds arrive at partner bank. Your funds may be divided in up to five (5) different banks, and you may be eligible for up to $1,250,000 of FDIC insurance (five banks, $250,000 per bank). If the number of available banks changes, and/or have existing assets at, one or more of the available banks, the actual amount could be higher or lower. For more information on FDIC insurance coverage, please visit www.FDIC.gov.
<h3> Transactions History and Disputes</h3>
All questions regarding EFT transactions or your User Account must be directed to help@ yourmccluredesigns.org.com and not to Synapse or its financial institution partners.  yourmccluredesigns.org is responsible for resolving issues and errors relating to transactions and account balances. If you wish to make a financial service complaint against  yourmccluredesigns.org, you may email help@synapsepay.com.

To report a complaint relating to Evolve Bank & Trust’s services, email help@ yourmccluredesigns.org.com.


<h3> User disputes </h3>
You are solely responsible for your interactions with other users of the Site (“Users”) both within the Site and outside of the Site. It is prohibited for Users to contact each other outside of the Site for purposes related to the funding activities on the Site. Consistent with this prohibition,  yourmccluredesigns.org and its affiliates expressly disclaim any responsibility for interactions between Users outside of the Site. We reserve the right, but have no obligation, to monitor interactions on the Site between you and other Users, as well as any disputes between you and other Users.


<h3> Termination/exclusion </h3>
You understand that the Services are provided as a courtesy to you and that we may modify, suspend or terminate all or a portion of the Services at any time in our discretion without prior notice to you. We reserve the right, in our sole discretion, to revoke, terminate or suspend any privileges associated with accessing the Services for any reason or for no reason whatsoever, including improper use of the Services or failure to comply with these Terms of Use, and to take any other action we deem appropriate. You agree that  yourmccluredesigns.org shall not be liable to you or any third party for any termination of your access to the Services. Account termination may result in the forfeiture and destruction of all information associated with your account. If you wish to terminate your account, you may do so by contacting  yourmccluredesigns.org’s customer service at help@ yourmccluredesigns.org.com. Any fees paid to  yourmccluredesigns.org are non-refundable, unless otherwise specified and you shall remain obligated to pay all outstanding charges, if any, relating to your use of the Site or Services incurred prior to such termination.


<h3> Visitor/user suggestions </h3>
You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information provided by you to  yourmccluredesigns.org (collectively, “Feedback”) are not confidential and you hereby grant to  yourmccluredesigns.org a worldwide, perpetual, irrevocable, royalty-free license to reproduce, display, perform, distribute, publish, modify, edit or otherwise use such Feedback as it deems appropriate, for any and all commercial or non-commercial purposes, in its sole discretion.


<h3> Links to other sites </h3>
The Site may permit you to link to other websites or resources on the Internet, and other websites or resources may contain links to the Site. When you access third party websites, you do so at your own risk. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party. We do not exercise control over third party websites, and you acknowledge that  yourmccluredesigns.org is not responsible or liable for the content, functions, accuracy, legality, appropriateness or any other aspect of such websites or resources. These other websites may place their own cookies or other files on your computer, collect data or solicit personal information from you. Other websites follow different rules regarding the use or disclosure of the personal information you submit to them. We encourage you to read the privacy policies or statements of the other websites you visit. Please be aware that the terms of our Privacy Policy do not apply to these third-party websites.


<h3> Your ability to accept this user agreement </h3>
This Site is intended solely for users who are at least 18 years of age or older. By using the Site, you affirm that you are 18 years of age or older and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in this User Agreement, and to abide by and comply with this User Agreement.


<h3> Not intended as financial or investment advice </h3>
The Services are not intended as financial or investment advice. By providing the Services,  yourmccluredesigns.org does not intend to provide financial, investment, legal or tax advice and/or any other advice of any kind. Your use of the Services and any decisions you make to lend or invest money relating to opportunities addressed in the Content are at your sole risk. Lending money and investing in securities can expose you risk of loss up to the amount lent or invested.


<h3> Not to be construed as solicitation or recommendation </h3>
Content not to be construed as solicitation or recommendation.  yourmccluredesigns.org does not have investment banking relationships, conduct market making activities, engage in proprietary trading, or have any ownership of any securities issued by a publicly traded company that is the subject of the Services.  yourmccluredesigns.org’s and its affiliates’ officers, associated persons, or members of their families, may at any time be long or short, purchase or sell, or own options, rights or warrants in any securities of the publicly traded companies discussed in any Content, and may make purchases or sales of these securities.  yourmccluredesigns.org has no assets under management and is not registered as an investment adviser or broker-dealer with the securities and exchange commission or any state securities regulator. Investment advisory services are provided by  yourmccluredesigns.org Management, LLC, an investment adviser registered with the Securities and Exchange Commission. Financial advisory services are only provided to clients of  yourmccluredesigns.org Management, LLC pursuant to a written advisory agreement.

Content is meant for informational purposes only. Neither the Content nor any opinions expressed therein are a solicitation to purchase or sell any securities or for any other investment-related services. You should consult your portfolio managers, analysts, investment advisers, financial advisors, accountants, attorneys, or investment committees, as applicable, responsible for management of applicable assets before acting on information made available on or through the Services. Content contains forward looking predictions that are subject to certain risks and uncertainties which could cause actual results to differ materially from those currently anticipated or projected. Prices are subject to change at any time.  yourmccluredesigns.org provides Content to you in an effort to provide comprehensive information of a range of possible investment opportunities. Securities discussed in the Content are not suitable for all investors due to different needs, objectives, and financial resources. The securities mentioned may not be registered in every state. Investors should consider these factors when making an investment decision. Any questions regarding the Content must be addressed to  yourmccluredesigns.org using the contact information set forth in our Privacy Policy. Information obtained from independent sources other than  yourmccluredesigns.org (including without limitation, newspapers, magazines, and the internet is furnished for informational purposes only;  yourmccluredesigns.org has not prepared such sources or approved their contents. The information contained in the Content was obtained from sources believed to be reliable; however,  yourmccluredesigns.org does not guarantee its accuracy or completeness. Neither  yourmccluredesigns.org nor any of its affiliates renders tax or legal advice. As such, no one should act upon any tax or legal information contained in the Content without consulting a tax professional or attorney.

You acknowledge and agree that (a)  yourmccluredesigns.org and the individuals and entities that indirectly or directly own and/or control or are employed by  yourmccluredesigns.org, or are under common ownership and/or control with  yourmccluredesigns.org, may lend or invest in transactions described in the Content or may and typically will own and/or control the special purpose vehicles that borrow from investors or issue securities described in the Content and (b) the ownership and control relationships described in clause (a) of this sentence may create conflicts between your interests and those of  yourmccluredesigns.org and/or the parties that own, control or are under common control with or employed by  yourmccluredesigns.org. You agree to review and analyze all opportunities to invest or lend related to  yourmccluredesigns.org, including without limitation by consulting professionals and experts as described in the preceding paragraph, before agreeing to lend or invest. You agree and acknowledge that any resulting transaction creates an arm’s length relationship between  yourmccluredesigns.org and you and does not create any fiduciary or agency relationship or obligation on the part of  yourmccluredesigns.org or any individual or entity affiliated with  yourmccluredesigns.org through ownership or control.


<h3> Disclaimer of warranty </h3>
Access to the Services is provided “as is” and “as available” without any warranty of any kind, express or implied. To the fullest extent permissible pursuant to applicable law,  yourmccluredesigns.org, its affiliates and any person associated with  yourmccluredesigns.org and its affiliates, disclaims all warranties of any kind, either express or implied, statutory or otherwise, including but not limited to any implied warranties of title, merchantability, fitness for a particular purpose or non-infringement. Without limiting the foregoing,  yourmccluredesigns.org does not warrant that access to the Services will be uninterrupted or error-free, or that defects, if any, will be corrected; nor does  yourmccluredesigns.org, its affiliates, nor any person associated with  yourmccluredesigns.org or its affiliates, make any representations about the accuracy, reliability, currency, quality, completeness, usefulness, performance, security, legality or suitability of the Services, that defects will be corrected, that our Site or the server that makes it available are free of viruses or other harmful components or that the Site or any Services or items obtained through the Site will otherwise meet your needs or expectations. You expressly agree that your use of the Services is at your sole risk. You shall be solely and fully responsible for any damage to any computer system, any loss of data, or any improper use or improper disclosure of information caused by you or any person using your login credentials.  yourmccluredesigns.org cannot and does not assume any responsibility for any loss, damages or liabilities arising from the failure of any telecommunications infrastructure, or the internet or for your misuse of any of advice, ideas, information, instructions or guidelines accessed through the Services.
You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the Site will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to the Site for any reconstruction of any lost data. We will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of the Site or any Services or other proprietary material due to your use of the Site or any Services or items obtained through the Site or to your downloading of any material posted on it, or any website linked to it.


<h3> Limitation of liability </h3>
 yourmccluredesigns.org and its parents, subsidiaries, affiliates, officers, directors, agents or employees are not liable to you or any other person for any punitive, exemplary, consequential, incidental, indirect or special damages (including, without limitation, any personal injury, lost profits, business interruption, loss of programs or other data on your computer or otherwise) arising from or in connection with your use of the Services, whether under a theory of breach of contract, tort, negligence, strict liability, malpractice, any other legal or equitable theory or otherwise, even if  yourmccluredesigns.org has been advised of the possibility of such damages. You hereby release  yourmccluredesigns.org and hold it and its parents, subsidiaries, affiliates, officers, directors, agents and employees harmless from any and all claims, demands, and damages of every kind and nature (including, without limitation, actual, special, incidental and consequential), known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with your use of the Services. You waive the provisions of any state or local law limiting or prohibiting a general release.
The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction. This limitation of liability also applies with respect to damages incurred by you by reason of any products or services sold or provided on any linked sites or otherwise by third parties other than  yourmccluredesigns.org and received through the Services or any linked sites.


<h3> Exclusive remedy </h3>
Without limiting the limitation of liability above, in the event of any problem with the Services, you agree that your sole and exclusive remedy is to cease using the Services. Under no circumstances shall  yourmccluredesigns.org, its parents, subsidiaries, affiliates, officers, directors, agents or employees be liable in any way for your use of Services, including, but not limited to, any errors or omissions in the Services, any infringement by the Services of the intellectual property rights or other rights of third parties, or for any loss or damage of any kind incurred as a result of the use of the Services. Certain states and/or jurisdictions do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, so the exclusions set forth above may not apply to you.



<h3> Indemnification </h3>
Without limiting the generality or effect of other provisions of this User Agreement, as a condition of use, you agree to indemnify, hold harmless, and defend  yourmccluredesigns.org and its parents, subsidiaries, affiliates, suppliers, lenders, licensors or service providers and, in each case, their officers, directors, affiliates, subcontractors, agents and employees, lenders, licensors and suppliers and their parents, subsidiaries, affiliates, suppliers and their officers, directors, affiliates, subcontractors, agents and employees (collectively, “Indemnified Parties” and each, individually, an “Indemnified Party”) against all costs, expenses, liabilities and damages (including reasonable attorney’s fees) incurred by any Indemnified Party in connection with any third party claims arising out of: (i) your use of the Services; (ii) your failure to comply with any applicable laws and regulations; and (iii) your breach of any obligations set forth in this User Agreement. You shall not settle any such claim without the written consent of the applicable Indemnified Party.

If you are a California resident, you waive California Civil Code Section 1542, which says: “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.” If you are a resident of another jurisdiction, you waive any comparable statute or doctrine.

This defense and indemnification obligation shall survive this User Agreement and your use of the Service.  yourmccluredesigns.org reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with  yourmccluredesigns.org in asserting any available defenses.


<h3>  yourmccluredesigns.org Mobile Program Terms and Conditions </h3>
The  yourmccluredesigns.org text message service (the “Text Service”) is operated by  yourmccluredesigns.org. Your use of the Text Service constitutes your agreement to these terms and conditions (“Mobile Terms”). The  yourmccluredesigns.org Terms of Use and Privacy Policy also apply to your use of the Text Service. We may modify or cancel the Text Service or any of its features without notice. We may also modify these Mobile Terms at any time and your continued use of the Text Service following the effective date of any such changes shall constitute your acceptance of such changes.

 yourmccluredesigns.org does not charge for the Text Service, but you are responsible for all charges and fees associated with text messaging imposed by your wireless provider. Message and Data Rates May Apply. Text messages may be sent using an automatic telephone dialing system or other technology. Your consent to receive autodialed marketing text messages is not required as a condition of purchasing any goods or services or investing in any offering on the  yourmccluredesigns.org Platform. If you have opted-in, the Text Service provides mobile text alerts relating to (i) account status and notifications, (ii) offering notices, investment status and reminders, (iii) technology-related product updates and (iv) marketing and advertising communications. The Service is a recurring message program. Message frequency will vary. You may receive multiple messages per month. Text the single keyword command STOP to cancel at any time. You’ll receive a one-time opt-out confirmation text message. If you have subscribed to other  yourmccluredesigns.org mobile message programs and wish to cancel, you will need to opt-out separately from those programs by following the instructions provided in their respective mobile terms. For Text Service support or assistance, text HELP to our Program short code, or call our customer support team at help@ yourmccluredesigns.org.com.

You acknowledge that any messages, including any STOP or HELP requests, you send to a short code or telephone number we have changed may not be received and  yourmccluredesigns.org will not be responsible for honoring requests made in such messages.

The wireless carriers supported by the Text Service are not liable for delayed or undelivered messages. You agree to provide us with a valid mobile number. If you change your mobile phone number, you agree to opt out of the Text Service prior to changing your mobile number.

You agree to indemnify, defend, and hold us and our affiliates harmless from any third party claims, liability, damages or costs arising from your use of the Text Service or from you providing us with a phone number that is not your own.

You agree that we will not be liable for failed, delayed, or misdirected delivery of any information sent through the Text Service; any errors in such information; and/or any action you may or may not take in reliance on the information or Text Service.

<h2> Service. </h2>

<h3> Wire Transfers </h3>
<p> A. Security Procedures. All Users are required to use a Two-Factor Authentication control, in addition to their login, to authorize a wire transfer using  yourmccluredesigns.org. You agree that Two-Factor Authentication is an appropriate security procedure, designed to verify the authenticity of the order, and not to detect errors in transmission. </p>

<p> B. Cutoff Times. All domestic wire requests are subject to a cutoff time of 12:00pm PST and shall be processed on business days only. </p>

<p> C. No Cancellation. All wire requests are final and are not subject to recall orders or stop payments. </P>

<p> D. Payment Order. Users may only initiate a wire transaction via  yourmccluredesigns.org’s website. The User is solely responsible for the accuracy of the information contained in the payment order. The wire transaction will be completed relying exclusively on the information provided by the User. </p>

<p> E. Authorization. By initiating any wire transaction via the Platform Services, you authorize Evolve to execute payment orders on your behalf and to debit the account you specify in the payment order for the amount of the wire transfer. </p>


<p> Governing law and jurisdiction </p>
This User Agreement shall be governed by the laws of the State of New York without regard to its rules on conflicts or choice of law that would require or permit the application of the laws of any other jurisdiction. By agreeing to these Terms of Use and using the Site and the Services, you agree to submit to personal jurisdiction in New York for all purposes, the exclusive jurisdiction of the New York courts and you agree to waive, to maximum extent permitted by law, any right to a trial by jury for any matter. You and  yourmccluredesigns.org agree that each may bring claims against the other only in your or its individual capacity, and not as a plaintiff or class member in any purported class or representative proceeding. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this User Agreement. You understand that you may consult with counsel about agreeing to this User Agreement, and you agree that by using the Site, and the Services, you are voluntarily accepting the User Agreement.



<p> Miscellaneous </p>
This User Agreement constitutes the sole agreement between you and  yourmccluredesigns.org for your use and the provision of the Services and the subject matter hereof, and no representations, statements or inducements, oral or written, not contained in this User Agreement shall bind either you or  yourmccluredesigns.org. Any of the terms of this User Agreement which are determined to be invalid, unlawful, void, or for any reason unenforceable shall be ineffective to the extent of such invalidity or unenforceability, without rendering invalid or unenforceable any of the remaining terms of this User Agreement or affecting the validity or enforceability of this User Agreement as a whole. Failure to insist on performance of any of the terms of this User Agreement will not operate as a waiver of any subsequent default. No waiver by  yourmccluredesigns.org of any right under this User Agreement will be deemed to be either a waiver of any other right or provision or a waiver of that same right or provision at any other time. You may not assign, transfer or delegate your rights or obligations hereunder, in whole or in part. This User Agreement shall be binding upon and inure to the benefit of each of the parties and the parties’ respective successors and permitted assigns. A printed version of this User Agreement and of any related notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this User Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. By using the Site, you agree to Google’s Terms of Service.


<h3> Disclaimer </h3>
No communication by  yourmccluredesigns.org, through the Site or any other medium, should be construed or is intended to be a recommendation to purchase, sell or hold any security or otherwise to be investment, tax, financial, accounting, legal, regulatory or compliance advice. Nothing on the Site is intended as an offer to extend credit, an offer to purchase or sell securities or a solicitation of any securities transaction. Investing in securities described in the Content on the Site poses risks, including but not limited to credit risk, interest rate risk, and the risk of losing some or all of the money you invest. Before investing in any securities you should: (1) conduct your own investigation and analysis; (2) carefully consider the investment and all related charges, expenses, uncertainties and risks, including all uncertainties and risks described in offering materials; and (3) consult with your own investment, tax, financial and legal advisors. The securities described in the Content on the Site are only suitable for accredited investors who understand and are willing and able to accept the high risks associated with private investments. Investing in private placements requires long-term commitments, the ability to afford to lose the entire investment, and low liquidity needs. This Site provides preliminary and general information about such securities and is intended for initial reference purposes only. It does not summarize or compile all the applicable information. This Site does not constitute an offer to sell or buy any securities. No offer or sale of any securities will occur without the delivery of confidential offering materials and related documents. The information contained herein is qualified by and subject to more detailed information in the applicable offering materials.  yourmccluredesigns.org is not registered as an investment adviser or broker-dealer.  yourmccluredesigns.org does not make any representation or warranty to any prospective investor regarding the legality or suitability of an investment in any securities.





 </div>
	  
<br><br><br><br><br><br>

<?php

require 'footer2.php';


?>